### ISSUE TITLE
Plugin isn't working on Windows 10

### ISSUE THREAD

**Issue by domasgru** [11ty/eleventy-plugin-vue#21]
Steps to reproduce:

1. Git clone this repo.
2. Try to run a sample, with command: `$env:ELEVENTY_EXPERIMENTAL="true";npx @11ty/eleventy --input=test/sample --serve` (the one in package json won't work on windows).
3. I get an eror:
`> You must supply options.input to rollup
Error was thrown:
    Error: You must supply options.input to rollup
        at Graph.generateModuleGraph (C:\Users\Domas\Desktop\eleventy-plugin-vue\node_modules\rollup\dist\shared\rollup.js:19096:19)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async Graph.build (C:\Users\Domas\Desktop\eleventy-plugin-vue\node_modules\rollup\dist\shared\rollup.js:19060:9)        at async rollupInternal (C:\Users\Domas\Desktop\eleventy-plugin-vue\node_modules\rollup\dist\shared\rollup.js:19980:9)
        at async EleventyVue.getBundle (C:\Users\Domas\Desktop\eleventy-plugin-vue\EleventyVue.js:124:18)
        at async Object.init (C:\Users\Domas\Desktop\eleventy-plugin-vue\.eleventy.js:99:22)`

**Comment by tusamni** [comment]
Ever figure anything out with this? I'm getting the same error.

**Comment by zachleat** [comment]
Shipping with 1.0.0-canary.6 (which uses Vue 3)
