### ISSUE TITLE
Cannot use with Postcss 8 plugins

### ISSUE THREAD

**Issue by philwolstenholme** [11ty/eleventy-plugin-vue#44]
#41 means that `rollup-plugin-vue` is not going to be updated, which causes an issue for Postcss users as `rollup-plugin-vue` uses [`rollup-plugin-postcss` version `3`](https://github.com/vuejs/rollup-plugin-vue/blob/next/package.json#L42) and `rollup-plugin-postcss` [only supports `postcss` version `7`](https://github.com/egoist/rollup-plugin-postcss/blob/v3.1.8/package.json#L59).

This means that if an 11ty user wants to use an up-to-date Postcss plugin (one that requires Postcss `8`) then they will get this sort of error:

```
[11ty] Error: PostCSS plugin autoprefixer requires PostCSS 8.
[11ty] Migration guide for end-users:
[11ty] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Error: PostCSS plugin autoprefixer requires PostCSS 8.
[11ty] Migration guide for end-users:
[11ty] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[11ty]     at Object.<anonymous> (/Users/phil/Sites/wolstenhol-11ty/node_modules/rollup-plugin-vue/dist/rollup-plugin-vue.js:273:35)
[11ty]     at Generator.next (<anonymous>)
[11ty]     at fulfilled (/Users/phil/Sites/wolstenhol-11ty/node_modules/rollup-plugin-vue/dist/rollup-plugin-vue.js:30:58)
```

**Comment by zachleat** [comment]
The Eleventy Vue Plugin 1.x canary supports this and will go stable soon. The downside here is that it requires Vue 3!
